#!/usr/bin/env sh

find_proj_root() {
  dir="$(pwd)"

  while :; do
    if [ -d "$dir/.git" ]; then
      echo "$dir"
      break
    fi

    if [ "$dir" = "/" ]; then
      echo "could not find project root"
      exit 1
    fi

    dir="$(dirname "$dir")"
  done
}

root="$(find_proj_root)"
style_file="$root/style.rb"

# we only want to scan staged files
md_files="$(git diff-index --cached --name-only HEAD | grep ".*\.md")"
errors="$(mdl --style "$style_file" $md_files)"

if [ -n "$errors" ]; then
  echo "$errors"
  exit 2
fi