#!/usr/bin/env sh

get_files() {
  files=
  unstaged="$(git diff --name-only)"

  for filename in $(git diff --name-only --staged); do
    if echo "$filename" | grep --quiet ".*\.md"; then
      if ! echo "$unstaged" | grep --line-regexp --quiet "$filename"; then
        files="$files $filename"
      else
        echo "there are unstaged changes to file '$filename', please stash or reset those changes" >&2
        exit 3
      fi
    fi

  done

  echo "$files"
}

find_proj_root() {
  dir="$(pwd)"

  while :; do
    if [ -d "$dir/.git" ]; then
      echo "$dir"
      break
    fi

    if [ "$dir" = "/" ]; then
      echo "could not find project root"
      exit 1
    fi

    dir="$(dirname "$dir")"
  done
}

root="$(find_proj_root)"
style_file="$root/style.rb"

# we only want to scan staged files
md_files="$(get_files)"
status_code=$?

if [ "$status_code" -ne 0 ]; then
  exit "$status_code"
fi

if [ -z "$md_files" ]; then
  exit
fi

errors="$(mdl --style "$style_file" $md_files)"

if [ -n "$errors" ]; then
  echo "$errors"
  exit 2
fi