apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: test-job
        image: alpine:latest
        command: ['sh', '-c', 'while :; do date "+%F %T %z"; sleep 5; done']
      restartPolicy: OnFailure