apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-kubedump
spec:
  containers:
    - name: test-pod
      image: alpine:latest
      command: ['sh', '-c', 'while :; do date "+%F %T %z"; sleep 5; done']
      imagePullPolicy: Always